add require time to avoid test failure
fix below test error (on Debian unstable)

> │ Run tests for ruby2.5 from debian/ruby-tests.rake                            │
>
> All examples were filtered out; ignoring {:focus=>true}
>      # ./spec/aruba/api_spec.rb:333:in `block (5 levels) in <top (required)>'
>
>      NoMethodError:
>        undefined method `parse' for Time:Class
>      Shared Example Group: "an existing directory" called from ./spec/aruba/api_spec.rb:388
>      # ./spec/aruba/api_spec.rb:386:in `block (7 levels) in <top (required)>'
>      # ./spec/aruba/api_spec.rb:381:in `block (6 levels) in <top (required)>'
>      # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'