rspec is required for step_definitions, not just spec'ing the library
Sample output from tests using aruba:
Then the output should contain "xyz" # aruba-0.2.7/lib/aruba/cucumber.rb:110
  undefined method `include' for #<Object:0x8113c62c> (NoMethodError)