Use assert_equal instead of Minitest's #must_equal
In order to fix the error that currently breaks the build:

  1) Error:
FirstRun#test_getting_started_with_aruba:
RuntimeError: Calling #must_equal outside of test.
    test/use_aruba_with_minitest.rb:18:in `test_getting_started_with_aruba'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips